const NAMESPACE_DEFAULT_NAME = 'NAMESPACE_DEFAULT_NAME'

const OUTPUT_FORMAT_TYPE_OBJECT = 'OUTPUT_FORMAT_TYPE_OBJECT'
const OUTPUT_FORMAT_TYPE_PG = 'OUTPUT_FORMAT_TYPE_PG'

const UNDEFINED_VALUE = (() => {return})()

const MAX_INT = 2147483647
const MIN_INT = -2147483648

module.exports = {
	NAMESPACE_DEFAULT_NAME,
	OUTPUT_FORMAT_TYPE_OBJECT,
	OUTPUT_FORMAT_TYPE_PG,
	UNDEFINED_VALUE,
	MAX_INT,
	MIN_INT
}
