const NAMESPACE_DEFAULT_NAME = 'NAMESPACE_DEFAULT_NAME'

const UNDEFINED_VALUE = (() => {return})()

const MAX_INT = 2147483647
const MIN_INT = -2147483648

module.exports = {
	NAMESPACE_DEFAULT_NAME,
	UNDEFINED_VALUE,
	MAX_INT,
	MIN_INT
}
